"""empty message

Revision ID: 06dd5b9ad56b
Revises: 707e71d64205
Create Date: 2020-10-15 17:02:42.291415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06dd5b9ad56b'
down_revision = '707e71d64205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('leaves', sa.Float(), nullable=True))
    op.drop_column('user', 'beans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('beans', mysql.FLOAT(), nullable=True))
    op.drop_column('user', 'leaves')
    # ### end Alembic commands ###
