"""empty message

Revision ID: b7099a366e68
Revises: 58083ee8ea81
Create Date: 2020-12-23 00:06:34.821737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7099a366e68'
down_revision = '58083ee8ea81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'pages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('pages', mysql.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
