"""empty message

Revision ID: ccdb1cce7b04
Revises: ad7e9c85f07b
Create Date: 2020-10-15 10:45:35.949124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdb1cce7b04'
down_revision = 'ad7e9c85f07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wx_avatar', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wx_avatar')
    # ### end Alembic commands ###
